# Generated by Django 5.2.8 on 2025-11-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the person contacting', max_length=200, verbose_name='Name')),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=200, null=True, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, help_text='Phone number (optional)', max_length=50, null=True, verbose_name='Telefon')),
                ('message', models.TextField(help_text='Message content', verbose_name='Nachricht')),
                ('consent', models.BooleanField(default=False, help_text='Data processing consent', verbose_name='Einwilligung')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date and time when the message was created', verbose_name='Erstellt am')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the message has been read', verbose_name='Gelesen')),
            ],
            options={
                'verbose_name': 'Kontaktnachricht',
                'verbose_name_plural': 'Kontaktnachrichten',
                'ordering': ['-created_at'],
            },
        ),
    ]
