# Generated by Django 5.2.8 on 2025-11-21 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, help_text='Message content (optional)', verbose_name='Nachricht'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the person contacting (optional)', max_length=200, verbose_name='Name'),
        ),
    ]
