# Generated by Django 5.2.8 on 2025-12-03 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_app', '0002_alter_contactmessage_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at'], 'verbose_name': 'İletişim Mesajı', 'verbose_name_plural': 'İletişim Mesajları'},
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='age',
            field=models.IntegerField(blank=True, help_text='Yaş bilgisi', null=True, verbose_name='Yaş'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='children_count',
            field=models.IntegerField(default=0, help_text='Çocuk sayısı', verbose_name='Çocuk Sayısı'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='driving_license',
            field=models.CharField(blank=True, help_text='Sürücü belgesi sınıfı', max_length=50, verbose_name='Sürücü Belgesi Sınıfı'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='graduation',
            field=models.CharField(blank=True, help_text='Mezuniyet bilgisi', max_length=200, verbose_name='Mezuniyet'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('bekar', 'Bekar'), ('evli', 'Evli')], help_text='Medeni durum', max_length=20, verbose_name='Medeni Durum'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='profession',
            field=models.CharField(blank=True, help_text='Meslek bilgisi', max_length=200, verbose_name='Meslek'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='consent',
            field=models.BooleanField(default=False, help_text='Veri işleme onayı', verbose_name='Onay'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Mesajın oluşturulduğu tarih ve saat', verbose_name='Oluşturulma tarihi'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(blank=True, help_text='E-posta adresi', max_length=200, null=True, verbose_name='E-Posta'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Mesajın okunup okunmadığı', verbose_name='Okundu'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.TextField(blank=True, help_text='Mesaj içeriği', verbose_name='Mesaj'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, help_text='İletişime geçen kişinin adı (isteğe bağlı)', max_length=200, verbose_name='Ad Soyad'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(blank=True, help_text='Telefon numarası (isteğe bağlı)', max_length=50, null=True, verbose_name='İrtibat Numarası'),
        ),
    ]
