# Generated by Django 5.2.8 on 2025-12-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_app', '0003_alter_contactmessage_options_contactmessage_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='age',
            field=models.IntegerField(help_text='Yaş bilgisi', verbose_name='Yaş'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='driving_license',
            field=models.CharField(help_text='Sürücü belgesi sınıfı', max_length=50, verbose_name='Sürücü Belgesi Sınıfı'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='email',
            field=models.EmailField(default='exit', help_text='E-posta adresi', max_length=200, verbose_name='E-Posta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='graduation',
            field=models.CharField(help_text='Mezuniyet bilgisi', max_length=200, verbose_name='Mezuniyet'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='marital_status',
            field=models.CharField(choices=[('bekar', 'Bekar'), ('evli', 'Evli')], help_text='Medeni durum', max_length=20, verbose_name='Medeni Durum'),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='profession',
            field=models.CharField(help_text='Meslek bilgisi', max_length=200, verbose_name='Meslek'),
        ),
    ]
