# Generated by Django 5.2.8 on 2025-12-29 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_app', '0004_alter_contactmessage_age_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Slider görseli', upload_to='slider/', verbose_name='Görsel')),
                ('title', models.CharField(help_text='Slider başlığı', max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(help_text='Slider açıklaması', verbose_name='Açıklama')),
                ('order', models.IntegerField(default=0, help_text='Görsellerin gösterim sırası (küçük sayı önce gösterilir)', verbose_name='Sıralama')),
                ('is_active', models.BooleanField(default=True, help_text="Bu görsel slider'da gösterilsin mi?", verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Görselin oluşturulduğu tarih ve saat', verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Görselin son güncellendiği tarih ve saat', verbose_name='Güncellenme tarihi')),
            ],
            options={
                'verbose_name': 'Slider Görseli',
                'verbose_name_plural': 'Slider Görselleri',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
