# Generated by Django 4.2.7 on 2026-01-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration_app', '0005_sliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Şirket adı', max_length=200, verbose_name='Şirket Adı')),
                ('company_type', models.CharField(blank=True, help_text='Şirket türü (örn: UG haftungsbeschränkt)', max_length=200, verbose_name='Şirket Türü')),
                ('address', models.TextField(help_text='Şirket adresi', verbose_name='Adres')),
                ('phone', models.CharField(help_text='Telefon numarası', max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(help_text='E-posta adresi', max_length=200, verbose_name='E-Posta')),
                ('website', models.URLField(blank=True, help_text="Web sitesi URL'i", verbose_name='Web Sitesi')),
                ('tax_id', models.CharField(blank=True, help_text='Vergi numarası veya USt-IdNr.', max_length=100, verbose_name='Vergi Numarası / USt-IdNr.')),
                ('trade_register', models.CharField(blank=True, help_text='Ticaret sicili bilgisi', max_length=200, verbose_name='Ticaret Sicili')),
                ('founder_name', models.CharField(help_text='Kurucu adı', max_length=200, verbose_name='Kurucu Adı')),
                ('founder_image', models.ImageField(blank=True, help_text='Kurucu görseli (Hakkımızda sayfasında gösterilir)', null=True, upload_to='founder/', verbose_name='Kurucu Görseli')),
                ('founder_bio', models.TextField(blank=True, help_text='Kurucu biyografisi (isteğe bağlı)', verbose_name='Kurucu Biyografisi')),
                ('is_active', models.BooleanField(default=True, help_text='Bu yapılandırma aktif mi?', verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Yapılandırmanın oluşturulduğu tarih ve saat', verbose_name='Oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Yapılandırmanın son güncellendiği tarih ve saat', verbose_name='Güncellenme tarihi')),
            ],
            options={
                'verbose_name': 'Uygulama Yapılandırması',
                'verbose_name_plural': 'Uygulama Yapılandırmaları',
                'ordering': ['-updated_at'],
            },
        ),
    ]
