"""
Django settings for integration_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# PythonAnywhere detection - check if we're on PythonAnywhere
# PythonAnywhere hosts are typically username.pythonanywhere.com
# Multiple detection methods for reliability
ON_PYTHONANYWHERE = (
    os.path.exists('/home') and 'pythonanywhere' in os.environ.get('HOME', '').lower()
) or (
    'pythonanywhere' in os.environ.get('HOSTNAME', '').lower()
) or (
    'pythonanywhere.com' in os.environ.get('HTTP_HOST', '').lower()
) or (
    config('ON_PYTHONANYWHERE', default=False, cast=bool)
)

# ALLOWED_HOSTS configuration
# For PythonAnywhere: Set your domain in environment variable or .env file
# Example: ALLOWED_HOSTS=yourusername.pythonanywhere.com
allowed_hosts_from_env = config('ALLOWED_HOSTS', default='').strip()
if allowed_hosts_from_env:
    # Split by comma and strip whitespace
    ALLOWED_HOSTS = [host.strip() for host in allowed_hosts_from_env.split(',') if host.strip()]
else:
    # Default to empty list - user must configure ALLOWED_HOSTS
    # On PythonAnywhere, you'll need to add your domain: username.pythonanywhere.com
    ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'integration_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'integration_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'integration_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': str(BASE_DIR / 'db.sqlite3'),  # Convert to string for cross-platform compatibility
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr'  # Turkish only

TIME_ZONE = 'UTC'

USE_I18N = False

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Absolute path to the directory static files should be collected to.
# Don't put anything in this directory yourself; store your static files
# in apps' "static/" subdirectories and in STATICFILES_DIRS.
# On PythonAnywhere, this will be served from /static/ URL
STATIC_ROOT = str(BASE_DIR / 'staticfiles')

# Additional locations of static files
STATICFILES_DIRS = [
    # You can add additional static file directories here if needed
    # BASE_DIR / 'static',
]

# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = str(BASE_DIR / 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email Configuration - ElasticEmail
# https://elasticemail.com/support/smtp-settings/

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.elasticemail.com')

# PythonAnywhere port kısıtlamaları: Sadece 587 ve 465 portlarına izin verilir
# Port 2525 PythonAnywhere'de çalışmaz, bu yüzden otomatik olarak 587'ye geçiyoruz
if ON_PYTHONANYWHERE:
    # PythonAnywhere'de port 587 (TLS) kullan
    EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
    EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)
else:
    # Local'de port 2525 kullanabiliriz
    EMAIL_PORT = config('EMAIL_PORT', default=2525, cast=int)
    EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
    EMAIL_USE_SSL = config('EMAIL_USE_SSL', default=False, cast=bool)

EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_TIMEOUT = 30

# Default email address for sending emails
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default=EMAIL_HOST_USER)
SERVER_EMAIL = config('SERVER_EMAIL', default=EMAIL_HOST_USER)

# Admin email addresses (comma-separated)
ADMIN_NAME = config('ADMIN_NAME', default='Admin')
ADMIN_EMAIL = config('ADMIN_EMAIL', default='')
ADMINS = [
    (ADMIN_NAME, ADMIN_EMAIL),
] if ADMIN_EMAIL else []

# Managers email addresses (comma-separated)
MANAGERS = ADMINS

# Email sending settings
# Set to False to disable sending confirmation emails to users (useful for test accounts)
# Şimdilik sadece admin'e mail gönderilecek, kullanıcıya gönderilmeyecek
SEND_USER_CONFIRMATION_EMAIL = config('SEND_USER_CONFIRMATION_EMAIL', default=False, cast=bool)